### ISSUE TITLE
Running example

### ISSUE THREAD

**Issue by NofelYaseen** [khundman/telemanom#32]
I am trying to run the example in Readme

`python example.py -l labeled_anomalies.csv`

I get the error:

> Traceback (most recent call last):
>   File "example.py", line 1, in <module>
>     from telemanom.detector import Detector
>   File "/Users/nofelyaseen/mount/vincentserver/telemanom/telemanom/detector.py", line 224
>     result_row = {**result_row,
>                    ^
> SyntaxError: invalid syntax

**Comment by NofelYaseen** [comment]
Nvm, it works with python3
