### ISSUE TITLE
Help to solve errors

### ISSUE THREAD

**Issue by MuhammadTalmeez337** [khundman/telemanom#66]
Hi sir, I am running your project and I am facing these errors. Can you help me?  I would be very thankful to you. Thanks

> Traceback (most recent call last):
  File "example.py", line 10, in <module> detector.run()
  File "C:\Users\Muhammad Talmeez\telemanom\telemanom\detector.py", line 210, in run errors.process_batches(channel)
  File "C:\Users\Muhammad Talmeez\telemanom\telemanom\errors.py", line 141, in process_batches window.prune_anoms()
  File "C:\Users\Muhammad Talmeez\telemanom\telemanom\errors.py", line 418, in prune_anoms  
 E_seq = np.delete(E_seq, i_to_remove, axis=0)
  File "<__array_function__ internals>", line 5, in delete
  File "C:\Users\Muhammad Talmeez\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\lib\function_base.py", line 4406, in delete
    keep[obj,] = False
IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by ZhouHnag** [comment]
I met with the same, have you solved the problem?

**Comment by ZhouHnag** [comment]
I met with the same problem, have you solved it?

**Comment by MuhammadTalmeez337** [comment]
> No sir, I am still stuck.

**Comment by ZhouHnag** [comment]
I consider that it may be caused by the uncorrected version of numpy. After installing numpy-1.17.4, the issue disappeared.

**Comment by khundman** [comment]
Thanks @ZhouHnag. @MuhammadTalmeez337 let me know if this resolves your issue and I will close.

**Comment by MuhammadTalmeez337** [comment]
I did not try this yet but I think if @ZhouHnag solved this. I also solve this. So sir @khundman you can close this. Thanks

**Comment by MuhammadTalmeez337** [comment]
> Thanks @ZhouHnag. @MuhammadTalmeez337 let me know if this resolves your issue and I will close.


I did not try this yet but I think if @ZhouHnag solved this. I will also solve this. So @khundman
